<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ShadcnBlazor.Extras\ShadcnBlazor.Extras.csproj" />
      <ProjectReference Include="..\ShadcnBlazor\ShadcnBlazor.csproj" />
    </ItemGroup>

</Project>
