<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.11"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ShadcnBlazor.Extras\ShadcnBlazor.Extras.csproj" />
      <ProjectReference Include="..\ShadcnBlazor\ShadcnBlazor.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Components\Highlight.razor" />
      <AdditionalFiles Include="Components\Showcase.razor" />
      <AdditionalFiles Include="ExtraShowcases\AlertDialogSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\AlertSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\ComboboxSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\Components\ExampleDialog.razor" />
      <AdditionalFiles Include="ExtraShowcases\CrashHandlerSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\DialogSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\EditorSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\FileDropzoneSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\FormHandlerSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\InputTagsSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\LazyLoaderSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\ToastSc1.razor" />
      <AdditionalFiles Include="ExtraShowcases\WButtonSc1.razor" />
      <AdditionalFiles Include="Partials\AppHeader.razor" />
      <AdditionalFiles Include="Partials\AppSidebar.razor" />
      <AdditionalFiles Include="Partials\MainLayout.razor" />
      <AdditionalFiles Include="Partials\NavUser.razor" />
      <AdditionalFiles Include="Showcases\AccordionSc1.razor" />
      <AdditionalFiles Include="Showcases\AlertDialogSc1.razor" />
      <AdditionalFiles Include="Showcases\AlertSc1.razor" />
      <AdditionalFiles Include="Showcases\AvatarSc1.razor" />
      <AdditionalFiles Include="Showcases\BadgeSc1.razor" />
      <AdditionalFiles Include="Showcases\BreadcrumbSc1.razor" />
      <AdditionalFiles Include="Showcases\ButtonGroupSc1.razor" />
      <AdditionalFiles Include="Showcases\ButtonSc1.razor" />
      <AdditionalFiles Include="Showcases\CalendarSc1.razor" />
      <AdditionalFiles Include="Showcases\CardSc1.razor" />
      <AdditionalFiles Include="Showcases\CarouselSc1.razor" />
      <AdditionalFiles Include="Showcases\CheckboxSc1.razor" />
      <AdditionalFiles Include="Showcases\CollapsibleSc1.razor" />
      <AdditionalFiles Include="Showcases\CommandSc1.razor" />
      <AdditionalFiles Include="Showcases\ContextMenuSc1.razor" />
      <AdditionalFiles Include="Showcases\DataGridSc1.razor" />
      <AdditionalFiles Include="Showcases\DatePickerSc1.razor" />
      <AdditionalFiles Include="Showcases\DialogSc1.razor" />
      <AdditionalFiles Include="Showcases\DrawerSc1.razor" />
      <AdditionalFiles Include="Showcases\DropdownMenuSc1.razor" />
      <AdditionalFiles Include="Showcases\EmptySc1.razor" />
      <AdditionalFiles Include="Showcases\HoverCardSc1.razor" />
      <AdditionalFiles Include="Showcases\InputGroupSc1.razor" />
      <AdditionalFiles Include="Showcases\InputOTPSc1.razor" />
      <AdditionalFiles Include="Showcases\InputSc1.razor" />
      <AdditionalFiles Include="Showcases\ItemSc1.razor" />
      <AdditionalFiles Include="Showcases\KbdSc1.razor" />
      <AdditionalFiles Include="Showcases\LabelSc1.razor" />
      <AdditionalFiles Include="Showcases\MenubarSc1.razor" />
      <AdditionalFiles Include="Showcases\NativeSelectSc1.razor" />
      <AdditionalFiles Include="Showcases\PaginationSc1.razor" />
      <AdditionalFiles Include="Showcases\PopoverSc1.razor" />
      <AdditionalFiles Include="Showcases\ProgressSc1.razor" />
      <AdditionalFiles Include="Showcases\RadioGroupSc1.razor" />
      <AdditionalFiles Include="Showcases\SelectSc1.razor" />
      <AdditionalFiles Include="Showcases\SeparatorSc1.razor" />
      <AdditionalFiles Include="Showcases\SheetSc1.razor" />
      <AdditionalFiles Include="Showcases\SkeletonSc1.razor" />
      <AdditionalFiles Include="Showcases\SliderSc1.razor" />
      <AdditionalFiles Include="Showcases\SonnerSc1.razor" />
      <AdditionalFiles Include="Showcases\SpinnerSc1.razor" />
      <AdditionalFiles Include="Showcases\SwitchSc1.razor" />
      <AdditionalFiles Include="Showcases\TableSc1.razor" />
      <AdditionalFiles Include="Showcases\TabsSc1.razor" />
      <AdditionalFiles Include="Showcases\TextareaSc1.razor" />
      <AdditionalFiles Include="Showcases\ToggleGroupSc1.razor" />
      <AdditionalFiles Include="Showcases\ToggleSc1.razor" />
      <AdditionalFiles Include="Showcases\TooltipSc1.razor" />
      <AdditionalFiles Include="Views\Components\AccordionDemo.razor" />
      <AdditionalFiles Include="Views\Components\AlertDemo.razor" />
      <AdditionalFiles Include="Views\Components\AlertDialogDemo.razor" />
      <AdditionalFiles Include="Views\Components\AvatarDemo.razor" />
      <AdditionalFiles Include="Views\Components\BadgeDemo.razor" />
      <AdditionalFiles Include="Views\Components\BreadcrumbDemo.razor" />
      <AdditionalFiles Include="Views\Components\ButtonDemo.razor" />
      <AdditionalFiles Include="Views\Components\ButtonGroupDemo.razor" />
      <AdditionalFiles Include="Views\Components\CalendarDemo.razor" />
      <AdditionalFiles Include="Views\Components\CardDemo.razor" />
      <AdditionalFiles Include="Views\Components\CarouselDemo.razor" />
      <AdditionalFiles Include="Views\Components\CheckboxDemo.razor" />
      <AdditionalFiles Include="Views\Components\CollapsibleDemo.razor" />
      <AdditionalFiles Include="Views\Components\CommandDemo.razor" />
      <AdditionalFiles Include="Views\Components\ContextMenuDemo.razor" />
      <AdditionalFiles Include="Views\Components\DataTableDemo.razor" />
      <AdditionalFiles Include="Views\Components\DatePickerDemo.razor" />
      <AdditionalFiles Include="Views\Components\DialogDemo.razor" />
      <AdditionalFiles Include="Views\Components\DrawerDemo.razor" />
      <AdditionalFiles Include="Views\Components\DropdownMenuDemo.razor" />
      <AdditionalFiles Include="Views\Components\EmptyDemo.razor" />
      <AdditionalFiles Include="Views\Components\HoverCardDemo.razor" />
      <AdditionalFiles Include="Views\Components\Index.razor" />
      <AdditionalFiles Include="Views\Components\InputDemo.razor" />
      <AdditionalFiles Include="Views\Components\InputGroupDemo.razor" />
      <AdditionalFiles Include="Views\Components\InputOTPDemo.razor" />
      <AdditionalFiles Include="Views\Components\ItemDemo.razor" />
      <AdditionalFiles Include="Views\Components\KbdDemo.razor" />
      <AdditionalFiles Include="Views\Components\LabelDemo.razor" />
      <AdditionalFiles Include="Views\Components\MenubarDemo.razor" />
      <AdditionalFiles Include="Views\Components\NativeSelectDemo.razor" />
      <AdditionalFiles Include="Views\Components\PaginationDemo.razor" />
      <AdditionalFiles Include="Views\Components\PopoverDemo.razor" />
      <AdditionalFiles Include="Views\Components\ProgressDemo.razor" />
      <AdditionalFiles Include="Views\Components\RadioGroupDemo.razor" />
      <AdditionalFiles Include="Views\Components\SelectDemo.razor" />
      <AdditionalFiles Include="Views\Components\SeparatorDemo.razor" />
      <AdditionalFiles Include="Views\Components\SheetDemo.razor" />
      <AdditionalFiles Include="Views\Components\SkeletonDemo.razor" />
      <AdditionalFiles Include="Views\Components\SliderDemo.razor" />
      <AdditionalFiles Include="Views\Components\SonnerDemo.razor" />
      <AdditionalFiles Include="Views\Components\SpinnerDemo.razor" />
      <AdditionalFiles Include="Views\Components\SwitchDemo.razor" />
      <AdditionalFiles Include="Views\Components\TableDemo.razor" />
      <AdditionalFiles Include="Views\Components\TabsDemo.razor" />
      <AdditionalFiles Include="Views\Components\TextareaDemo.razor" />
      <AdditionalFiles Include="Views\Components\ToggleDemo.razor" />
      <AdditionalFiles Include="Views\Components\ToggleGroupDemo.razor" />
      <AdditionalFiles Include="Views\Components\TooltipDemo.razor" />
      <AdditionalFiles Include="Views\Extras\AlertDemo.razor" />
      <AdditionalFiles Include="Views\Extras\AlertDialogDemo.razor" />
      <AdditionalFiles Include="Views\Extras\ComboboxDemo.razor" />
      <AdditionalFiles Include="Views\Extras\CrashHandlerDemo.razor" />
      <AdditionalFiles Include="Views\Extras\DialogDemo.razor" />
      <AdditionalFiles Include="Views\Extras\EditorDemo.razor" />
      <AdditionalFiles Include="Views\Extras\FileDropzoneDemo.razor" />
      <AdditionalFiles Include="Views\Extras\FormHandlerDemo.razor" />
      <AdditionalFiles Include="Views\Extras\Index.razor" />
      <AdditionalFiles Include="Views\Extras\InputTagsDemo.razor" />
      <AdditionalFiles Include="Views\Extras\LazyLoaderDemo.razor" />
      <AdditionalFiles Include="Views\Extras\ToastDemo.razor" />
      <AdditionalFiles Include="Views\Extras\WButtonDemo.razor" />
      <AdditionalFiles Include="Views\Index.razor" />
      <AdditionalFiles Include="Views\Installation.razor" />
    </ItemGroup>

</Project>
