name: "NPM: publish"

on:
  workflow_dispatch:
  push:
    paths:
      - "ShadcnBlazor.Test/Styles/shadcnblazor/package.json"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    # OIDC for npm publishing
    permissions:
      id-token: write
      contents: read
    
    steps:
      ## Setup environment:
      
      # Fetch the code
      - uses: actions/checkout@v5
        
      # Install nodejs/npm
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      ## Build:
      
      # Build styles
      - run: npm i
        working-directory: ShadcnBlazor.Test/Styles

      - run: npm run build
        working-directory: ShadcnBlazor.Test/Styles

      ## Publishing:

      # shadcnblazor
      - uses: JS-DevTools/npm-publish@v4
        with:
          package: "ShadcnBlazor.Test/Styles/shadcnblazor"